### ISSUE TITLE
Can't pickup a failed message if next one is successful

### ISSUE THREAD

**Issue by Lonebuddha** [verpeta/php-kafka-intro#1]
Hello,

Thank you for the nice repository! I am very interested in such solution and appreciate your work.

Could you clarify how it works in case of a failure of a specific message handling? For instance:
- message 1 is processed successfully
- message 2 failed (because of a fail in one of downstream services), but the consumer keeps working
- message 3 is processed successfully
- and I want to try to process message 2 again

Is there an architecture to achieve this using Kafka?

**Comment by verpeta** [comment]
Hello, thanks for your question)
I suggest that you will work with this the same way as with MySQL transactions, you must not commit message to Kafka before you are fully sure that you successfully process message.

$msg = $topic->consume($partition, 1000);
try{
   //Process your message like store to DB
    // And only after it commit offset
   
    $topic->offsetStore($partition, $msg->offset);

} catch Exception {
//log error
}

Commit - must be on the last line of your try-catch
